FROM python:3.10-slim

WORKDIR /app

COPY requirements-ui.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY app_ui.py .
COPY fa_IR-amir-medium.onnx .
COPY fa_IR-amir-medium.onnx.json .

EXPOSE 8501

CMD ["streamlit", "run", "app_ui.py", "--server.port=8501", "--server.address=0.0.0.0"]
